###########################################################################
#                                                                         #
# MAKE FILE FOR NBEZ.EXE                                                  #
#                                                                         #
# HISTORY:                                                                #
#                                                                         #
#  12-05-92 - copied from the NBBASE makefile                             #
#                                                                         #
#  Rick Fishman                                                           #
#  Code Blazers, Inc.                                                     #
#  4113 Apricot                                                           #
#  Irvine, CA. 92720                                                      #
#  CIS ID: 72251,750                                                      #
#                                                                         #
###########################################################################

BASE=nbez

CFLAGS=/Q+ /Ss /W3 /Kbcepr /Ti+ /O- /C
LFLAGS=/NOI /MAP /DE /NOL /A:16 /EXEPACK /BASE:65536

.SUFFIXES: .c

.c.obj:
    icc $(CFLAGS) $*.c

$(BASE).exe: $*.obj $*.def $*.res
    link386 $(LFLAGS) $*,,, os2386, $*
    rc $*.res $*.exe

$(BASE).res: $*.rc $*.dlg
    rc -r $*

$(BASE).obj: $*.c $*.h

###########################################################################
#                       E N D   O F   S O U R C E                         #
###########################################################################
