# nmake makefile
# 
# Tools used:
#  Compile::Resource Compiler
#  Compile::GNU C
#  Make: nmake
all : nbez.exe

nbez.exe : nbez.obj nbez.res nbez.def
	gcc -Zomf nbez.obj nbez.res nbez.def -o nbez.exe
	wrc nbez.res

nbez.obj : nbez.c nbez.h
	gcc -Wall -Zomf -DOS2EMX_PLAIN_CHAR -c -O2 nbez.c -o nbez.obj

nbez.res : nbez.rc
	wrc -r nbez.rc

clean :
	rm -rf *exe *RES *obj